name: "Download BDS"
description: "Downloads BDS and extracts its content in provided directory"
author: "ConMaster2112"
inputs:
  out-dir:
    description: "Directory for BDS installation"
    required: true
    default: sus
  version:
    description: "Specific BDS version or tag"
    required: true
    default: "latest"
  
  use-preview:
    description: "When ever to use preview or stable, true === preview"
    required: true
    default: false

runs:
  using: "node20"
  main: "dist/main.js"
