name: "Download BDS"
description: "Downloads BDS and extracts its content in provided directory"
author: "ConMaster2112"
inputs:
  out_dir:
    description: "Directory for BDS installation"
    required: true
    default: bds_bin

  version:
    description: "Specific BDS version or tag"
    required: true
    default: "latest"
  
  use_preview:
    description: "When ever to use preview or stable, true === preview"
    required: true
    default: false

runs:
  using: "node20"
  main: "dist/main.js"

branding:
  icon: 'arrow-down-circle'
  color: 'black'