name: "Test BDS Download"

on:
    workflow_dispatch:

jobs:
    main-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./
            - name: Test Case
              run: ls -R .
