name: "Test BDS Download"

on:
    workflow_dispatch:

jobs:
    linux-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./
              with:
                out_dir: "bin"
                version: 1.21.40.25
                use_preview: true
            - name: Test Case
              run: ls ./bin/
            - uses: bedrock-apis/bds-download@v1
              with:
                out_dir: "bin2"
                version: 1.21.40.25
                use_preview: true
            - name: Test Case 2
              run: ls ./bin2/
    windows-test:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./
              with:
                out_dir: "bin"
                version: 1.21.40.25
                use_preview: true
            - name: Test Case
              run: dir ./bin/
